import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
// import "@/app/global.css";
import NavMenu from "./components/NavMenu/NavMenu";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Base App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})


export default async function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  if(!session) {
    redirect('/sign-in')
  }

    return (
        <div>
            <NavMenu/>
            <div className="flex flex-col items-center justify-center pt-[67px]">
                {children}  
            </div>
        </div>
    );
}
