import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import NavMenu from "../components/NavMenu/NavMenu";
import AuthProvider from "./AuthProvider";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { SideMenu } from "@/components/SIdeMenu/SideMenu";

export const metadata: Metadata = {
  title: "Base App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})
const sidebarNavItems = [
  {
    title: "Profile",
    href: "/settings/profile",
  },
  {
    title: "Account",
    href: "/settings/account",
  },
  {
    title: "Appearance",
    href: "/settings/appearance",
  },
  {
    title: "Notifications",
    href: "/settings/notifications",
  },
  {
    title: "Display",
    href: "/settings/display",
  },
]

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log(session?.user.role);
  return (
    <AuthProvider>
      <html lang="en">
        <body className={cn(
          "min-h-screen font-sans antialiased" 
        )}>
          <main className="flex flex-col justify-center items-center pt-[67px]">
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>
                {session?.user.role == 'admin' ? (
                  <SideMenu items={sidebarNavItems} />
                ): <NavMenu/>}
                {children}  
            </ThemeProvider>
          </main>
          <Toaster/>
        </body>
      </html>
    </AuthProvider>
  );
}
