import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import NavMenu from "../components/NavMenu/NavMenu";
import AuthProvider from "./AuthProvider";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Base App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={cn(
          "min-h-screen font-sans antialiased" 
        )}>
          <main className="flex flex-col justify-center items-center pt-[67px]">
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>
                <NavMenu/>
                {children}  
            </ThemeProvider>
          </main>
          <Toaster/>
        </body>
      </html>
    </AuthProvider>
  );
}
